import { generateScript, generateTTS } from '@/lib/openai';
import { prisma } from '@/lib/prisma';
import { parseJSON, sleep } from '@/lib/utils';
import type { VideoGenerationConfig, GeneratedScript, ContentEngineResult } from '@/types';

export class ContentVideoEngine {
  private projectId: string;
    private config: VideoGenerationConfig;

      constructor(projectId: string, config: VideoGenerationConfig) {
          this.projectId = projectId;
              this.config = config;
                }

                  async generate(): Promise<ContentEngineResult> {
                      try {
                            // Step 1: Create video record
                                  const video = await prisma.video.create({
                                          data: {
                                                    projectId: this.projectId,
                                                              title: `Video sobre ${this.config.topic}`,
                                                                        status: 'GENERATING_SCRIPT',
                                                                                },
                                                                                      });

                                                                                            // Step 2: Generate script
                                                                                                  const scriptJson = await generateScript(
                                                                                                          this.config.topic,
                                                                                                                  this.config.style,
                                                                                                                          this.config.duration,
                                                                                                                                  this.config.language
                                                                                                                                        );
                                                                                                                                        
                                                                                                                                              const script = parseJSON<GeneratedScript>(scriptJson, {
                                                                                                                                                      title: this.config.topic,
                                                                                                                                                              description: '',
                                                                                                                                                                      tags: [],
                                                                                                                                                                              segments: [],
                                                                                                                                                                                      totalDuration: 300,
                                                                                                                                                                                            });
                                                                                                                                                                                            
                                                                                                                                                                                                  // Update video with script
                                                                                                                                                                                                        await prisma.video.update({
                                                                                                                                                                                                                where: { id: video.id },
                                                                                                                                                                                                                        data: {
                                                                                                                                                                                                                                  title: script.title,
                                                                                                                                                                                                                                            script: script.segments.map((s) => s.text).join('\n\n'),
                                                                                                                                                                                                                                                      status: 'GENERATING_AUDIO',
                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                          // Step 3: Generate audio for each segment
                                                                                                                                                                                                                                                                                const scenes = [];
                                                                                                                                                                                                                                                                                      for (let i = 0; i < script.segments.length; i++) {
                                                                                                                                                                                                                                                                                              const segment = script.segments[i];
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      // Create scene record
                                                                                                                                                                                                                                                                                                              const scene = await prisma.scene.create({
                                                                                                                                                                                                                                                                                                                        data: {
                                                                                                                                                                                                                                                                                                                                    videoId: video.id,
                                                                                                                                                                                                                                                                                                                                                order: i,
                                                                                                                                                                                                                                                                                                                                                            text: segment.text,
                                                                                                                                                                                                                                                                                                                                                                        duration: segment.duration,
                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                  scenes.push(scene);
                                                                                                                                                                                                                                                                                                                                                                                                          await sleep(500); // Rate limiting
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                      // Step 4: Update to rendering status
                                                                                                                                                                                                                                                                                                                                                                                                                            await prisma.video.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                    where: { id: video.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                            data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: 'RENDERING',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                duration: script.totalDuration,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description: script.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tags: script.tags,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Step 5: Mark as completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await prisma.video.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              where: { id: video.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      data: { status: 'COMPLETED' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { success: true, videoId: video.id };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('ContentVideoEngine error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  error: error instanceof Error ? error.message : 'Unknown error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                static async getStatus(videoId: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return prisma.video.findUnique({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          where: { id: videoId },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                include: { scenes: { orderBy: { order: 'asc' } } },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
