import { generateScript } from '@/lib/openai';
import { prisma } from '@/lib/prisma';
import { parseJSON, sleep } from '@/lib/utils';
import type { VideoGenerationConfig, GeneratedScript, ContentEngineResult } from '@/types';

export class ContentShortEngine {
  private projectId: string;
    private config: VideoGenerationConfig;

      constructor(projectId: string, config: VideoGenerationConfig) {
          this.projectId = projectId;
              this.config = { ...config, duration: 'short' };
                }

                  async generate(): Promise<ContentEngineResult> {
                      try {
                            // Create video record for short
                                  const video = await prisma.video.create({
                                          data: {
                                                    projectId: this.projectId,
                                                              title: `Short: ${this.config.topic}`,
                                                                        status: 'GENERATING_SCRIPT',
                                                                                  metadata: { type: 'short', format: '9:16' },
                                                                                          },
                                                                                                });

                                                                                                      // Generate short-form script (max 60 seconds)
                                                                                                            const shortPrompt = `${this.config.topic} - formato YouTube Shorts (menos de 60 segundos, muito impactante e direto ao ponto)`;
                                                                                                                  const scriptJson = await generateScript(
                                                                                                                          shortPrompt,
                                                                                                                                  this.config.style,
                                                                                                                                          'short',
                                                                                                                                                  this.config.language
                                                                                                                                                        );
                                                                                                                                                        
                                                                                                                                                              const script = parseJSON<GeneratedScript>(scriptJson, {
                                                                                                                                                                      title: this.config.topic,
                                                                                                                                                                              description: '',
                                                                                                                                                                                      tags: [],
                                                                                                                                                                                              segments: [],
                                                                                                                                                                                                      totalDuration: 60,
                                                                                                                                                                                                            });
                                                                                                                                                                                                            
                                                                                                                                                                                                                  // Limit to max 60 seconds for shorts
                                                                                                                                                                                                                        const shortSegments = script.segments.slice(0, 3);
                                                                                                                                                                                                                              const totalDuration = Math.min(
                                                                                                                                                                                                                                      shortSegments.reduce((acc, s) => acc + s.duration, 0),
                                                                                                                                                                                                                                              60
                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          await prisma.video.update({
                                                                                                                                                                                                                                                                  where: { id: video.id },
                                                                                                                                                                                                                                                                          data: {
                                                                                                                                                                                                                                                                                    title: script.title,
                                                                                                                                                                                                                                                                                              script: shortSegments.map((s) => s.text).join(' '),
                                                                                                                                                                                                                                                                                                        status: 'GENERATING_AUDIO',
                                                                                                                                                                                                                                                                                                                  duration: totalDuration,
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                      // Create scenes for each segment
                                                                                                                                                                                                                                                                                                                                            for (let i = 0; i < shortSegments.length; i++) {
                                                                                                                                                                                                                                                                                                                                                    const segment = shortSegments[i];
                                                                                                                                                                                                                                                                                                                                                            await prisma.scene.create({
                                                                                                                                                                                                                                                                                                                                                                      data: {
                                                                                                                                                                                                                                                                                                                                                                                  videoId: video.id,
                                                                                                                                                                                                                                                                                                                                                                                              order: i,
                                                                                                                                                                                                                                                                                                                                                                                                          text: segment.text,
                                                                                                                                                                                                                                                                                                                                                                                                                      duration: Math.min(segment.duration, 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                await sleep(300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                            await prisma.video.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    where: { id: video.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: 'COMPLETED',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type: 'short',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        format: '9:16',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: script.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tags: [...script.tags, '#Shorts', '#YouTube'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { success: true, videoId: video.id };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('ContentShortEngine error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              error: error instanceof Error ? error.message : 'Unknown error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            static async getStatus(videoId: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return prisma.video.findUnique({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      where: { id: videoId },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            include: { scenes: { orderBy: { order: 'asc' } } },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
