import { translateText, generateTTS } from '@/lib/openai';
import { prisma } from '@/lib/prisma';
import { sleep } from '@/lib/utils';
import type { TranslationConfig, ContentEngineResult } from '@/types';

export class ContentTranslationEngine {
  private videoId: string;
    private config: TranslationConfig;

      constructor(videoId: string, config: TranslationConfig) {
          this.videoId = videoId;
              this.config = config;
                }

                  async translate(): Promise<ContentEngineResult> {
                      try {
                            const video = await prisma.video.findUnique({
                                    where: { id: this.videoId },
                                            include: { scenes: { orderBy: { order: 'asc' } } },
                                                  });

                                                        if (!video) {
                                                                return { success: false, error: 'Video not found' };
                                                                      }

                                                                            // Create translated video project
                                                                                  const translatedVideo = await prisma.video.create({
                                                                                          data: {
                                                                                                    projectId: video.projectId,
                                                                                                              title: `[${this.config.targetLanguage.toUpperCase()}] ${video.title}`,
                                                                                                                        status: 'GENERATING_SCRIPT',
                                                                                                                                  metadata: {
                                                                                                                                              originalVideoId: this.videoId,
                                                                                                                                                          sourceLanguage: this.config.sourceLanguage,
                                                                                                                                                                      targetLanguage: this.config.targetLanguage,
                                                                                                                                                                                  isTranslation: true,
                                                                                                                                                                                            },
                                                                                                                                                                                                    },
                                                                                                                                                                                                          });
                                                                                                                                                                                                          
                                                                                                                                                                                                                // Translate each scene
                                                                                                                                                                                                                      const translatedScenes = [];
                                                                                                                                                                                                                            for (let i = 0; i < video.scenes.length; i++) {
                                                                                                                                                                                                                                    const scene = video.scenes[i];
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            const translatedText = await translateText(
                                                                                                                                                                                                                                                      scene.text,
                                                                                                                                                                                                                                                                this.config.targetLanguage,
                                                                                                                                                                                                                                                                          this.config.sourceLanguage
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                          const translatedScene = await prisma.scene.create({
                                                                                                                                                                                                                                                                                                    data: {
                                                                                                                                                                                                                                                                                                                videoId: translatedVideo.id,
                                                                                                                                                                                                                                                                                                                            order: scene.order,
                                                                                                                                                                                                                                                                                                                                        text: translatedText,
                                                                                                                                                                                                                                                                                                                                                    imageUrl: scene.imageUrl,
                                                                                                                                                                                                                                                                                                                                                                duration: scene.duration,
                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                          translatedScenes.push(translatedScene);
                                                                                                                                                                                                                                                                                                                                                                                                  await sleep(500);
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                              // Translate main script if exists
                                                                                                                                                                                                                                                                                                                                                                                                                    let translatedScript = null;
                                                                                                                                                                                                                                                                                                                                                                                                                          if (video.script) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  translatedScript = await translateText(
                                                                                                                                                                                                                                                                                                                                                                                                                                            video.script,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.config.targetLanguage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.config.sourceLanguage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await prisma.video.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            where: { id: translatedVideo.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              script: translatedScript,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration: video.duration,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'COMPLETED',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return { success: true, videoId: translatedVideo.id };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('ContentTranslationEngine error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      error: error instanceof Error ? error.message : 'Unknown error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    static getSupportedLanguages(): Array<{ code: string; name: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { code: 'pt-BR', name: 'Portugues (Brasil)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { code: 'en', name: 'English' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { code: 'es', name: 'Espanol' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { code: 'fr', name: 'Francais' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { code: 'de', name: 'Deutsch' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { code: 'it', name: 'Italiano' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { code: 'ja', name: 'Japanese' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { code: 'ko', name: 'Korean' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { code: 'zh', name: 'Chinese' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { code: 'ar', name: 'Arabic' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { code: 'ru', name: 'Russian' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
